// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJH2szZJo-lvzOZ0BkZ4N69yhteSxW1m4',
    appId: '1:834515432222:web:f38fafcc728bebe2678f0f',
    messagingSenderId: '834515432222',
    projectId: 'workpulse-515b0',
    authDomain: 'workpulse-515b0.firebaseapp.com',
    storageBucket: 'workpulse-515b0.firebasestorage.app',
    measurementId: 'G-J52XFEWJ06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu9A_cE0iBP-berYdNBqRejjsHh9u4Qn0',
    appId: '1:834515432222:android:b159e4a1b1d3809a678f0f',
    messagingSenderId: '834515432222',
    projectId: 'workpulse-515b0',
    storageBucket: 'workpulse-515b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjYCn1EH7sFlrM09S48HMz2Yr1g0McofY',
    appId: '1:834515432222:ios:328288d234cf92da678f0f',
    messagingSenderId: '834515432222',
    projectId: 'workpulse-515b0',
    storageBucket: 'workpulse-515b0.firebasestorage.app',
    androidClientId: '834515432222-bkn2n37ilbpa82r0hqekol2cgahi4ug4.apps.googleusercontent.com',
    iosClientId: '834515432222-7cmvjulh0qvnfn2sjatmev6rq5vfv6au.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjYCn1EH7sFlrM09S48HMz2Yr1g0McofY',
    appId: '1:834515432222:ios:328288d234cf92da678f0f',
    messagingSenderId: '834515432222',
    projectId: 'workpulse-515b0',
    storageBucket: 'workpulse-515b0.firebasestorage.app',
    androidClientId: '834515432222-bkn2n37ilbpa82r0hqekol2cgahi4ug4.apps.googleusercontent.com',
    iosClientId: '834515432222-7cmvjulh0qvnfn2sjatmev6rq5vfv6au.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJH2szZJo-lvzOZ0BkZ4N69yhteSxW1m4',
    appId: '1:834515432222:web:7e56ecca03df2cd4678f0f',
    messagingSenderId: '834515432222',
    projectId: 'workpulse-515b0',
    authDomain: 'workpulse-515b0.firebaseapp.com',
    storageBucket: 'workpulse-515b0.firebasestorage.app',
    measurementId: 'G-G3KLPHFKBE',
  );
}
